name: build

on: 
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt update
        sudo apt install npm
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        export PATH=~/.npm-global/bin:$PATH
        NPM_CONFIG_PREFIX=~/.npm-global
        npm install -g @vue/cli
        npm i
        npm run build
    - name: Copy CNAME
      run: |
        echo 'glosa-admin.andros.dev' > docs/CNAME
    - name: Upload docs
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add docs
        git commit -m 'Update build'
        git push origin master
